// oreo-nws-svelte/src/components/favorites.svelte
<script lang="ts">    
    import { createEventDispatcher } from 'svelte'
	import type { GeoLocation } from "src/models/GeoLocation";
    import Container from "./container.svelte";
    import { favorites, delFavorite, setCurrentFav } from "../stores/favoriteStore";

    const dispatch = createEventDispatcher();

     function onLocationClick(location: GeoLocation) {

        // Save the currently selected favorite...
        setCurrentFav(location)

        // Raise the location selected event...
        dispatch('locationSelected', location)
    }

    function onLocationDelClick(location: GeoLocation) {
        delFavorite(location)        
    }

</script>

{#if $favorites?.length > 0}
<div id="favorites" />
<Container title="">    
    <table class="w-full">    
        {#each $favorites as favorite }
            <tr >                       
                <td class="">
                    <a on:click={() => onLocationClick(favorite)} href="#weather">{favorite.name}</a>&nbsp;{favorite.state}, {favorite.country}
                </td>
                <td class="content-end text-right">
                    <!-- svelte-ignore a11y-invalid-attribute -->
                    <a on:click={() => onLocationDelClick(favorite)} href="#">🗑️</a>
                </td>                        
            </tr>             
        {/each}
    </table>
</Container>
{/if}

// oreo-openweather-vue/src/components/Favorites.vue
<script lang="ts">
import { defineComponent } from 'vue'
import type { GeoLocation } from '@/models/GeoLocation'
import { useFavoritesStore } from '@/stores/favorites'
import ContentBox from './ContentBox.vue'

export default defineComponent({
    name: "Favorites",
    setup() {
        const favoriteStore = useFavoritesStore();
        return { favoriteStore };
    },
    data() {
        return {
            favorites: [] as GeoLocation[],
        };
    },
    emits: {
        onLocationChanged(location: GeoLocation) { return location; }
    },
    methods: {
        async selectLocation(location: GeoLocation) {
            this.$emit("onLocationChanged", location);
        },
    },
    components: { ContentBox }
})
</script>

<template>
    <ContentBox id="favorites" v-if="favoriteStore.favorites?.length > 0" title="Favorite Locations">
        <div>
            <table class="w-full">    
                <TransitionGroup name="favs">            
                    <tr v-for="location in favoriteStore.favorites" :key="location.lat + location.lon">                       
                        <td class="">
                            <a @click="selectLocation(location)" href="#weather">{{location.name}}</a>&nbsp;{{location.state}}, {{location.country}}
                        </td>
                        <td class="content-end text-right">
                            <a @click="favoriteStore.delFovorite(location)" href="#favorites" alt="Nuke Favorite">🗑️</a>
                        </td>                        
                    </tr>             
                </TransitionGroup>   
            </table>
        </div>
    </ContentBox>
</template>

<style scoped>

.favs-enter-active, .favs-leave-active {
  transition: all 1s ease;
}

.favs-enter-from, .favs-leave-to {
  opacity: 0;
  transform: translateX(30px);
}

</style>
